module.exports = {
  apps: [{
    name: 'fdh-backend',
    cwd: '/opt/FDHChecker',
    script: 'server/dist/server/index.js',
    instances: 1,
    exec_mode: 'fork',
    autorestart: true,
    max_memory_restart: '1G',
    kill_timeout: 35000,
    listen_timeout: 10000,
    env: {
      NODE_ENV: 'production',
      PORT: 3506,
    },
    output: '/var/log/fdh-checker/api-output.log',
    error: '/var/log/fdh-checker/api-error.log',
    merge_logs: true,
    time: true,
  }, {
    name: 'fdh-frontend',
    cwd: '/opt/FDHChecker',
    script: 'node_modules/vite/bin/vite.js',
    args: 'preview --host 0.0.0.0 --port 3507 --strictPort',
    instances: 1,
    exec_mode: 'fork',
    autorestart: true,
    max_memory_restart: '512M',
    env: {
      NODE_ENV: 'production',
    },
    output: '/var/log/fdh-checker/frontend-output.log',
    error: '/var/log/fdh-checker/frontend-error.log',
    merge_logs: true,
    time: true,
  }],
};
